export const CATEGORY_MAPPINGS = {
  COOLER: "Freezer",
  "ICE LINED REFRIGERATOR": "Freezer",
  "COOLER AND FREEZER": "Freezer",
  "CHEST COOLER": "Freezer",
  MEDICAL: "Freezer",
  EUTECTIC: "Freezer",
  ILR: "Freezer",
  "VACCINE FREEZER": "Freezer",
  DUAL: "Freezer",
  FREEZER: "Freezer",
  "Choc Cooler": "Choc Cooler",
  "VISI COOLER": "VISI COOLER",
  "2 GLASS DOOR UNDERCOUNTER REFRIGERATOR": "SUS",
  "1 DOOR UNDERCOUNTER REFRIGERATOR": "SUS",
  "2 DOOR UNDERCOUNTER REFRIGERATOR": "SUS",
  "3 DOOR UNDERCOUNTER REFRIGERATOR": "SUS",
  "STORAGE WATER COOLER": "SWC",
  "FOW MODELS": "FOW",
  "EUTECTIC FOW FREEZER": "FOW",
  Compact: "Compact",
  "Reach-In": "Reach-In",
};
